apiVersion: v1
kind: Pod 
metadata: 
  name: mavenrc
  labels:
    app1: devarc
    namespace: vasu
spec:
  containers:
  - name: container_rc
    image: dockervasu324/maven-web-application
    ports:
    targetport: 80
    - containerport: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: rcsvc
  namespace: vasu
spec:
 type: NodePort
 selector:
  app1: devarc
  port: 80
  NodePort: 30333