apiVersion: v1
kind: Pod
metadata:
 name: vasudevapp
 labels:
   app1: vasu
spec:
 containers:
 - name: devareddy
  image: dockervasu324/maven-web-application:1
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: NodePort
  selector:
   app1:vasu
  ports:
  - port: 80
    targetPort: 8080
